### ISSUE TITLE
Atualização Dados Sorteios das Loterias

### ISSUE THREAD

**Issue by Tjas2x** [guilhermeasn/loteria.json#1]
Pode verificar por que não está havendo as atualizações das loterias, pois já tem bastante sorteios que não estão atualizando.
Grato.

**Comment by guilhermeasn** [comment]
Acredito que a API da CEF está bloqueando os IPs do Github. Não estou conseguindo fazer mais as atualizações com o Github Actions.

**Comment by guilhermeasn** [comment]
Acredito que a API da CEF está bloqueando os IPs do Github. Não estou conseguindo fazer mais as atualizações com o Github Actions.
