### ISSUE TITLE
Atualização dados, motivo de não atualização

### ISSUE THREAD

**Issue by Tjas2x** [guilhermeasn/loteria.json#2]
Solicito informações do porquê não está mais atualizando os sorteios das loterias, pois faço uso de tais dados. 
Grato.

Luiz

**Comment by guilhermeasn** [comment]
Acredito que a API da CEF está bloqueando os IPs do Github. Não estou conseguindo fazer mais as atualizações com o Github Actions.

**Comment by Tjas2x** [comment]
Olá.
Que chato isso, heim?
Mas ja consegui alternativa com api heroku e está atualizando normalmente.

Em dom., 13 de out. de 2024 15:15, Guilherme Neves ***@***.***>
escreveu:
